apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    auditsink-to-rbac/source: auditsink
    auditsink-to-rbac/user: masud
  name: auditsink-to-rbac:masud
  namespace: default
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    auditsink-to-rbac/source: auditsink
    auditsink-to-rbac/user: masud
  name: auditsink-to-rbac:masud
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auditsink-to-rbac:masud
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: masud
  namespace: default
