apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    auditsink-to-rbac/source: auditsink
    auditsink-to-rbac/user: minikube-user
  name: auditsink-to-rbac:minikube-user
  namespace: kube-system
rules:
- apiGroups:
  - extensions
  - rbac.authorization.k8s.io
  - ""
  resources:
  - deployments
  - roles
  - rolebindings
  - namespaces
  verbs:
  - list
  - delete
  - get
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    auditsink-to-rbac/source: auditsink
    auditsink-to-rbac/user: minikube-user
  name: auditsink-to-rbac:minikube-user
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auditsink-to-rbac:minikube-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: minikube-user
  namespace: kube-system
